import { StyleSheet } from "react-native";
import { homeColors, homeSpacing } from "../home/theme.ts";

export const CATEGORY_COPY = {
  header: "Categories",
  createCategory: "+ Add Category",
  createPrompt: "New Category",
  createConfirm: "Create",
  createPlaceholder: "Category name",
  delete: "Delete category",
  deleteIcon: "×",
  deleteConfirmTitle: "Delete Category",
  deleteConfirmMessage: 'Delete "{name}"?',
  deleteBlockedTitle: "Has Items",
  deleteBlockedMessage: '"{name}" has {count} items. Move them first?',
  cancel: "Cancel",
  deleteAction: "Delete",
  ok: "OK",
  moveItems: "Move Items",
};

export const MOVE_COPY = {
  title: "Move Items",
  subtitle: 'Move {count} items from "{name}":',
  noItems: 'No items in "{name}"',
  selectTarget: "Select target:",
  noCategories: "No other categories",
  selectCategory: "Select a category",
  moveTo: "Move to {name}",
  cancel: "Cancel",
  close: "Close",
};

export const categoryStyles = StyleSheet.create({
  container: { flex: 1 },
  panel: { flex: 1, backgroundColor: homeColors.surface, borderRadius: 16, padding: homeSpacing.md, gap: homeSpacing.md },
  actions: { flexDirection: "row", alignItems: "center", gap: homeSpacing.sm },
  sortToggle: { flexDirection: "row", alignItems: "center", gap: homeSpacing.xs },
  sortLabel: { fontSize: 12, color: homeColors.muted },
  spacer: { flex: 1 },
  actionButton: { backgroundColor: homeColors.primary, paddingHorizontal: homeSpacing.md, paddingVertical: homeSpacing.sm, borderRadius: 8 },
  actionLabel: { color: homeColors.buttonText, fontSize: 14, fontWeight: "600" },
  scroll: { flex: 1 },
  list: { gap: homeSpacing.sm },
  card: { backgroundColor: homeColors.cardBg, borderRadius: 12, padding: homeSpacing.md, borderWidth: 1, borderColor: homeColors.border },
  cardInner: { flexDirection: "row", alignItems: "center", gap: homeSpacing.sm },
  cardBody: { flex: 1 },
  cardName: { fontSize: 16, fontWeight: "600", color: homeColors.text },
  itemCount: { fontSize: 14, color: homeColors.muted, marginRight: homeSpacing.xs },
  dragHandle: { paddingVertical: homeSpacing.xs, paddingHorizontal: homeSpacing.xs, alignItems: "center", justifyContent: "center" },
  dragHandleIcon: { fontSize: 20, color: homeColors.muted },
  dragHandleDisabled: { color: "#d3d3d3" },
  deleteButton: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  deleteIcon: { fontSize: 20, color: homeColors.danger, fontWeight: "bold" },
  relative: { position: "relative" as const },
  ghost: { position: "absolute" as const, zIndex: 10, elevation: 5, opacity: 0.85 },
  indicator: { position: "absolute" as const, left: -12, right: -12, height: 2, backgroundColor: "#000000", borderRadius: 1, zIndex: 15 },
});

export const moveStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", alignItems: "center", padding: homeSpacing.lg },
  modal: { backgroundColor: homeColors.surface, borderRadius: 16, padding: homeSpacing.lg, width: "100%", maxHeight: "80%" },
  title: { fontSize: 18, fontWeight: "700", color: homeColors.text, marginBottom: homeSpacing.sm },
  subtitle: { fontSize: 14, color: homeColors.text, marginBottom: homeSpacing.sm },
  itemsList: { maxHeight: 120, borderWidth: 1, borderColor: homeColors.border, borderRadius: 8, padding: homeSpacing.sm, marginBottom: homeSpacing.md },
  itemText: { fontSize: 13, color: homeColors.muted, paddingVertical: 2 },
  sortRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: homeSpacing.sm },
  sortLabel: { fontSize: 14, fontWeight: "600", color: homeColors.text },
  categoryList: { maxHeight: 150, marginBottom: homeSpacing.md },
  categoryItem: { padding: homeSpacing.sm, borderRadius: 8, borderWidth: 1, borderColor: homeColors.border, marginBottom: homeSpacing.xs },
  categorySelected: { borderColor: homeColors.primary, borderWidth: 2, backgroundColor: homeColors.primaryLight },
  categoryName: { fontSize: 14, color: homeColors.text },
  empty: { fontSize: 14, color: homeColors.muted, textAlign: "center", padding: homeSpacing.md },
  actions: { flexDirection: "row", gap: homeSpacing.sm },
  cancelButton: { flex: 1, padding: homeSpacing.sm, borderRadius: 8, borderWidth: 1, borderColor: homeColors.border, alignItems: "center" },
  cancelLabel: { fontSize: 14, color: homeColors.text },
  moveButton: { flex: 2, padding: homeSpacing.sm, borderRadius: 8, backgroundColor: homeColors.primary, alignItems: "center" },
  moveButtonDisabled: { backgroundColor: homeColors.muted },
  moveLabel: { fontSize: 14, color: homeColors.buttonText, fontWeight: "600" },
  closeButton: { padding: homeSpacing.sm, borderRadius: 8, backgroundColor: homeColors.primary, alignItems: "center", marginTop: homeSpacing.sm },
  closeLabel: { fontSize: 14, color: homeColors.buttonText, fontWeight: "600" },
});
