export const SPACE_MGMT_COPY = {
  title: "Manage Space",
  rename: "Rename",
  renamePrompt: "Rename space",
  renameConfirm: "Rename",
  users: "Users",
  invite: "Invite User",
  invitePrompt: "Invite someone to this space",
  inviteConfirm: "Send",
  invitePlaceholder: "email@example.com",
  inviteSent: "Invitation sent!",
  ok: "OK",
  remove: "Remove",
  leave: "Leave Space",
  delete: "Delete Space",
  confirmLeave: "Are you sure you want to leave this space?",
  confirmDelete: "Are you sure you want to delete this space?",
  confirmRemove: "Remove this user from the space?",
  confirm: "Confirm",
  cancel: "Cancel",
  cannotDeleteHasLists: "This space still has packing lists.",
  cannotDeleteHasUsers: "Remove other users first.",
} as const;
