import { StyleSheet } from "react-native";
import { homeColors, homeRadius, homeSpacing } from "./theme.ts";

export const filterSheetStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: homeSpacing.lg,
  },
  sheet: {
    width: "100%",
    maxWidth: 400,
    maxHeight: "70%",
    backgroundColor: homeColors.surface,
    borderRadius: homeRadius,
    padding: homeSpacing.md,
    gap: homeSpacing.md,
  },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  title: { fontSize: 18, fontWeight: "700", color: homeColors.text },
  clearText: { fontSize: 14, fontWeight: "600", color: homeColors.primary },
  list: { flexGrow: 0 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: homeColors.muted,
    marginTop: homeSpacing.sm,
    marginBottom: homeSpacing.xs,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: homeSpacing.sm,
    paddingVertical: homeSpacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: homeColors.border,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: homeColors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: { backgroundColor: homeColors.primary, borderColor: homeColors.primary },
  checkmark: { color: "#fff", fontSize: 14, fontWeight: "700" },
  toggleContainer: {
    flexDirection: "row",
    backgroundColor: homeColors.border,
    borderRadius: 20,
    padding: 3,
    marginBottom: homeSpacing.sm,
  },
  toggleContainerActive: { backgroundColor: homeColors.primary },
  toggleSelector: {
    position: "absolute",
    top: 3,
    left: 3,
    height: "100%",
    backgroundColor: homeColors.surface,
    borderRadius: 17,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleOption: { flex: 1, paddingVertical: homeSpacing.sm, alignItems: "center", borderRadius: 17, zIndex: 1 },
  toggleText: { fontSize: 14, fontWeight: "500", color: homeColors.muted },
  toggleTextInactive: { color: homeColors.buttonText },
  toggleTextSelected: { color: homeColors.text, fontWeight: "600" },
  rowText: { fontSize: 16, color: homeColors.text },
  empty: { fontSize: 14, color: homeColors.muted, textAlign: "center", paddingVertical: homeSpacing.md },
  doneButton: {
    alignSelf: "flex-end",
    paddingHorizontal: homeSpacing.md,
    paddingVertical: homeSpacing.sm,
    backgroundColor: homeColors.primary,
    borderRadius: homeRadius / 2,
  },
  doneText: { color: "#fff", fontSize: 16, fontWeight: "600" },
});
