import { StyleSheet } from "react-native";
import { homeColors, homeRadius, homeSpacing } from "./theme.ts";

export const filterSheetStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: homeSpacing.lg,
  },
  sheet: {
    width: "100%",
    maxWidth: 400,
    maxHeight: "70%",
    backgroundColor: homeColors.surface,
    borderRadius: homeRadius,
    padding: homeSpacing.md,
    gap: homeSpacing.md,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: { fontSize: 18, fontWeight: "700", color: homeColors.text },
  clearText: { fontSize: 14, fontWeight: "600", color: homeColors.primary },
  content: { flex: 1, minHeight: 0, gap: homeSpacing.md },
  list: { flex: 1, minHeight: 0 },
  listContent: { paddingBottom: homeSpacing.lg },
  section: { minHeight: 0 },
  categorySection: { maxHeight: 220 },
  memberSection: { flex: 1 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: homeColors.muted,
    marginBottom: homeSpacing.xs,
  },
  sectionList: { minHeight: 0 },
  sectionListContent: { paddingBottom: homeSpacing.sm },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: homeSpacing.sm,
    paddingVertical: homeSpacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: homeColors.border,
  },
  rowLast: { borderBottomWidth: 0 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: homeColors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: {
    backgroundColor: homeColors.primary,
    borderColor: homeColors.primary,
  },
  checkmark: { color: "#fff", fontSize: 14, fontWeight: "700" },
  rowText: { flex: 1, fontSize: 16, color: homeColors.text },
  rowAvatarImage: { width: 24, height: 24, borderRadius: 6 },
  empty: {
    fontSize: 14,
    color: homeColors.muted,
    textAlign: "center",
    paddingVertical: homeSpacing.md,
  },
  doneButton: {
    alignSelf: "flex-end",
    paddingHorizontal: homeSpacing.md,
    paddingVertical: homeSpacing.sm,
    backgroundColor: homeColors.primary,
    borderRadius: homeRadius / 2,
  },
  doneText: { color: "#fff", fontSize: 16, fontWeight: "600" },
});
