export const spaceCopy = {
  spacesTitle: "Spaces",
  switchSpace: "Switch Space",
  createSpace: "Create Space",
  createSpacePrompt: "Name your new space",
  createSpaceConfirm: "Create",
  createSpacePlaceholder: "Family trip",
  inviteUser: "Invite User",
  pendingInvites: "Pending Invitations",
  inviteFrom: "From",
  personalSpace: "Personal",
  chevron: " \u25BE",
  leaveSpace: "Leave Space",
  deleteSpace: "Delete Space",
  renamePrompt: "Rename space",
  renameConfirm: "Rename",
  invitePrompt: "Invite someone to this space",
  inviteConfirm: "Send",
  inviteSent: "Invitation sent!",
} as const;
