export const spaceCopy = {
  switchSpace: "Switch Space",
  createSpace: "Create Space",
  createSpacePrompt: "Name your new space",
  createSpaceConfirm: "Create",
  createSpacePlaceholder: "Family trip",
  invitePrompt: "Invite someone to this space",
  inviteConfirm: "Send",
  invitePlaceholder: "email@example.com",
  inviteTitle: "Invite User",
  inviteSent: "Invitation sent!",
  inviteSentOk: "OK",
  pendingInvites: "Pending Invitations",
  accept: "Accept",
  decline: "Decline",
  inviteFrom: "From",
  currentSpace: "Current",
  personalSpace: "Personal",
  chevron: " \u25BE",
  renameSpace: "Rename Space",
  renameSpaceConfirm: "Rename",
  deleteSpace: "Delete Space",
  leaveSpace: "Leave Space",
  removeUser: "Remove",
  users: "Users",
  confirmDelete: "Are you sure you want to delete this space?",
  confirmLeave: "Are you sure you want to leave this space?",
  confirmRemoveUser: "Remove this user from the space?",
  cannotDeleteHasLists: "Cannot delete: space has packing lists",
  cannotDeleteHasUsers: "Cannot delete: space has other users",
  confirm: "Confirm",
  cancel: "Cancel",
} as const;
