import { StyleSheet } from "react-native";
import { homeCopy } from "./copy.ts";
import { homeColors, homeRadius, homeSpacing } from "./theme.ts";

const colors = homeColors;
const spacing = homeSpacing;
export const HOME_COPY = homeCopy;

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.surface },
  content: { flex: 1 },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  home: { flex: 1, width: "100%", gap: spacing.sm },
  panel: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    paddingTop: 0,
    gap: spacing.md,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  panelBody: { flex: 1, minHeight: 0, gap: spacing.md },
  backButton: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    minWidth: spacing.lg * 3,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  backPlaceholder: { width: spacing.lg, height: spacing.lg },
  avatar: {
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: spacing.lg / 2,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarLabel: { color: colors.primaryForeground, fontWeight: "700" },
  avatarImage: {
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: spacing.lg / 2,
  },
  scroll: { flex: 1 },
  swipeWrapper: { flex: 1 },
  swipeContainer: { flex: 1 },
  list: { gap: spacing.xs, paddingTop: spacing.xs },
  listActions: { gap: spacing.sm },
  listActionButton: {
    alignSelf: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: homeRadius,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  listActionLabel: { fontSize: 16, fontWeight: "600", color: colors.text },
  listItem: { fontSize: 16, color: colors.text, paddingVertical: spacing.xs },
  activeItem: {
    backgroundColor: colors.primary,
    borderRadius: homeRadius / 2,
    color: colors.primaryForeground,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  category: {
    gap: spacing.xs,
    padding: spacing.sm,
    borderRadius: homeRadius,
    borderWidth: 1,
    borderColor: colors.border,
  },
  categoryImage: { width: 24, height: 24, borderRadius: 4 },
  categoryBody: {
    gap: spacing.xs,
    backgroundColor: "rgba(255,255,255,0.65)",
    borderRadius: homeRadius / 2,
    padding: spacing.xs,
  },
  itemContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  itemHighlight: {
    backgroundColor: homeColors.highlight,
    borderRadius: homeRadius / 2,
    marginHorizontal: -spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  itemHighlightOverlay: {
    position: "absolute" as const,
    top: 0,
    left: -spacing.xs,
    right: -spacing.xs,
    bottom: 0,
    marginHorizontal: 0,
    paddingHorizontal: 0,
  },
  itemBody: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  itemContent: { flex: 1, gap: 2 },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: spacing.lg,
    paddingVertical: spacing.xs,
  },
  checkbox: {
    width: spacing.md,
    height: spacing.md,
    borderRadius: spacing.xs,
  },
  detailLabel: {
    flex: 1,
    fontSize: 16,
    lineHeight: 18,
    color: colors.text,
    textAlignVertical: "center",
  },
  detailLabelChecked: {
    color: colors.muted,
    textDecorationLine: "line-through",
  },
  itemInput: {
    flex: 1,
    fontSize: 16,
    lineHeight: 18,
    color: colors.text,
    paddingVertical: 0,
    textAlignVertical: "center",
  },
  editable: { flex: 1, justifyContent: "center" },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  memberRowWrap: {
    flexWrap: "wrap",
    rowGap: spacing.xs,
  },
  memberBadge: {
    flexDirection: "row",
    alignItems: "center",
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.border,
    paddingHorizontal: spacing.xs,
    gap: spacing.xs,
    overflow: "hidden",
  },
  memberBadgeImage: { width: 16, height: 16, borderRadius: 8 },
  memberBadgeText: { fontSize: 10, fontWeight: "600", color: colors.text },
  memberBadgeTextChecked: { color: colors.buttonText },
  menuButton: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  menuIcon: { fontSize: 20, color: colors.muted, fontWeight: "700" },
  swipeAction: { width: spacing.lg * 3 },
  modalLabel: { fontSize: 14, fontWeight: "500", color: colors.muted },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: homeRadius / 2,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: 16,
    color: colors.text,
  },
  modalInputError: { borderColor: colors.danger },
  modalError: { fontSize: 12, color: colors.danger, marginTop: -spacing.xs },
  itemDragHandle: {
    width: spacing.lg,
    height: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  itemDragHandleIcon: {
    fontSize: 18,
    lineHeight: 18,
    color: colors.muted,
    marginTop: -1,
    textAlignVertical: "center",
  },
  itemGhost: {
    position: "absolute",
    zIndex: 10,
    elevation: 5,
    opacity: 0.85,
    backgroundColor: colors.surface,
    borderRadius: homeRadius / 2,
    left: spacing.xs,
    right: spacing.xs,
  },
  itemIndicator: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: homeColors.dropIndicator,
    borderRadius: 1,
    zIndex: 15,
  },
  categoryOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
});
