import { StyleSheet } from "react-native";
import {
  homeCardStyle,
  homeColors,
  homeMaxWidth,
  homeRadius,
  homeSpacing,
} from "./theme.ts";
import { homeCopy } from "./copy.ts";
const colors = homeColors, spacing = homeSpacing, maxWidth = homeMaxWidth;
export const HOME_COPY = homeCopy;
export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { flex: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.lg },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.sm },
  loadingText: { fontSize: 16, color: colors.muted, fontWeight: "500" },
  home: { flex: 1, alignSelf: "center", maxWidth, width: "100%", gap: spacing.lg },
  panel: { ...homeCardStyle, flex: 1, gap: spacing.md },
  panelHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  panelTitle: { flex: 1, fontSize: 20, fontWeight: "700", color: colors.text },
  backButton: { paddingVertical: spacing.xs, paddingHorizontal: spacing.sm, minWidth: spacing.lg * 3, alignItems: "flex-start", justifyContent: "center" },
  backPlaceholder: { width: spacing.lg * 3, height: spacing.lg },
  backText: { color: colors.primary, fontWeight: "600" },
  avatar: { width: spacing.lg, height: spacing.lg, borderRadius: spacing.lg / 2, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  avatarLabel: { color: "#ffffff", fontWeight: "700" },
  scroll: { flex: 1 },
  swipeWrapper: { flex: 1 },
  swipeContainer: { flex: 1 },
  sectionTitle: { fontSize: 20, fontWeight: "600", color: colors.text, textAlign: "center" },
  list: { gap: spacing.xs },
  listItem: { fontSize: 16, color: colors.text, paddingVertical: spacing.xs },
  activeItem: { backgroundColor: colors.primary, borderRadius: homeRadius / 2, color: "#ffffff", paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  category: { gap: spacing.xs, padding: spacing.sm, borderRadius: homeRadius, borderWidth: 1, borderColor: colors.border },
  categoryHeader: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: spacing.lg },
  categoryCheckboxWrapper: { position: "relative", width: spacing.md, height: spacing.md, justifyContent: "center", alignItems: "center" },
  categoryCheckboxIndicator: { position: "absolute", width: spacing.md * 0.6, height: 2, backgroundColor: colors.text, borderRadius: 2, top: spacing.md / 2 - 1, left: spacing.md * 0.2 },
  categoryTitle: { flex: 1, fontSize: 18, lineHeight: 20, fontWeight: "600", color: colors.text, textAlignVertical: "center" },
  categoryInput: { flex: 1, fontSize: 18, lineHeight: 20, fontWeight: "600", color: colors.text, paddingVertical: 0, textAlignVertical: "center" },
  addButton: { paddingHorizontal: spacing.sm, height: spacing.lg, borderRadius: spacing.xs, alignItems: "center", justifyContent: "center" },
  addLabel: { fontSize: 18, lineHeight: 18, fontWeight: "700", color: colors.muted },
  categoryBody: { gap: spacing.xs, backgroundColor: "rgba(255,255,255,0.65)", borderRadius: homeRadius / 2, padding: spacing.xs },
  detailItem: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: spacing.lg, paddingVertical: spacing.xs },
  checkbox: { width: spacing.md, height: spacing.md, borderRadius: spacing.xs },
  detailLabel: { flex: 1, fontSize: 16, lineHeight: 18, color: colors.text, textAlignVertical: "center" },
  detailLabelChecked: { color: colors.muted, textDecorationLine: "line-through" },
  itemInput: { flex: 1, fontSize: 16, lineHeight: 18, color: colors.text, paddingVertical: 0, textAlignVertical: "center" },
  editable: { flex: 1, justifyContent: "center" },
  deleteButton: { paddingHorizontal: spacing.xs, paddingVertical: spacing.xs },
  deleteLabel: { fontSize: 18, color: colors.muted, fontWeight: "700" },
  empty: { alignItems: "center", paddingVertical: spacing.md },
  emptyText: { fontSize: 16, color: colors.muted, fontWeight: "500", textAlign: "center" },
  swipeAction: { width: spacing.lg * 3 },
});
