import { StyleSheet } from "react-native";
import { homeCopy } from "./copy.ts";
import { homeCardStyle, homeColors, homeMaxWidth, homeRadius, homeSpacing } from "./theme.ts";

const colors = homeColors;
const spacing = homeSpacing;
const maxWidth = homeMaxWidth;
export const HOME_COPY = homeCopy;

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: { flex: 1, paddingHorizontal: spacing.lg, paddingVertical: spacing.lg },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.sm },
  loadingText: { fontSize: 16, color: colors.muted, fontWeight: "500" },
  home: { flex: 1, alignSelf: "center", maxWidth, width: "100%", gap: spacing.lg },
  panel: { ...homeCardStyle, flex: 1, gap: spacing.md },
  panelHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  panelTitle: { flex: 1, fontSize: 20, fontWeight: "700", color: colors.text },
  quickAdd: { alignSelf: "flex-start", paddingVertical: spacing.xs / 2 },
  quickAddLabel: { fontSize: 14, fontWeight: "500", color: colors.primary },
  backButton: { paddingVertical: spacing.xs, paddingHorizontal: spacing.sm, minWidth: spacing.lg * 3, alignItems: "flex-start", justifyContent: "center" },
  backPlaceholder: { width: spacing.lg * 3, height: spacing.lg },
  backText: { color: colors.primary, fontWeight: "600" },
  avatar: { width: spacing.lg, height: spacing.lg, borderRadius: spacing.lg / 2, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  avatarLabel: { color: "#ffffff", fontWeight: "700" },
  scroll: { flex: 1 },
  swipeWrapper: { flex: 1 },
  swipeContainer: { flex: 1 },
  list: { gap: spacing.xs, paddingTop: spacing.xs },
  listActions: { gap: spacing.sm },
  listActionButton: { alignSelf: "center", paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: homeRadius, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  listActionLabel: { fontSize: 16, fontWeight: "600", color: colors.text },
  listCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: homeRadius, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, gap: spacing.sm },
  listCardInner: { flexDirection: "row", alignItems: "center", gap: spacing.sm, flex: 1 },
  listCardBody: { flex: 1 },
  listDragHandle: { paddingVertical: spacing.xs, paddingHorizontal: spacing.xs, alignItems: "center", justifyContent: "center" },
  listDragHandleIcon: { fontSize: 18, color: colors.muted },
  listCardSelected: { borderColor: colors.primary, shadowColor: colors.primary, shadowOpacity: 0.15, shadowRadius: spacing.sm, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  listCardText: { flex: 1, gap: spacing.xs },
  listName: { fontSize: 18, fontWeight: "600", color: colors.text },
  listSummary: { fontSize: 14, color: colors.muted },
  listDeleteButton: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  listDeleteIcon: { fontSize: 18 },
  listItem: { fontSize: 16, color: colors.text, paddingVertical: spacing.xs },
  activeItem: { backgroundColor: colors.primary, borderRadius: homeRadius / 2, color: "#ffffff", paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  category: { gap: spacing.xs, padding: spacing.sm, borderRadius: homeRadius, borderWidth: 1, borderColor: colors.border },
  categoryHeader: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: spacing.lg },
  categoryCheckboxWrapper: { position: "relative", width: spacing.md, height: spacing.md, justifyContent: "center", alignItems: "center" },
  categoryCheckboxIndicator: { position: "absolute", width: spacing.md * 0.6, height: 2, backgroundColor: colors.text, borderRadius: 2, top: spacing.md / 2 - 1, left: spacing.md * 0.2 },
  itemCheckboxIndicator: { position: "absolute", width: spacing.md * 0.6, height: 2, backgroundColor: colors.text, borderRadius: 2, top: spacing.md / 2 - 1, left: spacing.md * 0.2 },
  categoryTitle: { flex: 1, fontSize: 18, lineHeight: 20, fontWeight: "600", color: colors.text, textAlignVertical: "center" },
  categoryInput: { flex: 1, fontSize: 18, lineHeight: 20, fontWeight: "600", color: colors.text, paddingVertical: 0, textAlignVertical: "center" },
  addButton: { paddingHorizontal: spacing.sm, height: spacing.lg, borderRadius: spacing.xs, alignItems: "center", justifyContent: "center" },
  addLabel: { fontSize: 18, lineHeight: 18, fontWeight: "700", color: colors.muted },
  categoryBody: { gap: spacing.xs, backgroundColor: "rgba(255,255,255,0.65)", borderRadius: homeRadius / 2, padding: spacing.xs },
  itemContainer: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingVertical: spacing.xs },
  itemContent: { flex: 1, gap: 2 },
  detailItem: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: spacing.lg, paddingVertical: spacing.xs },
  checkbox: { width: spacing.md, height: spacing.md, borderRadius: spacing.xs },
  detailLabel: { flex: 1, fontSize: 16, lineHeight: 18, color: colors.text, textAlignVertical: "center" },
  detailLabelChecked: { color: colors.muted, textDecorationLine: "line-through" },
  itemInput: { flex: 1, fontSize: 16, lineHeight: 18, color: colors.text, paddingVertical: 0, textAlignVertical: "center" },
  editable: { flex: 1, justifyContent: "center" },
  memberRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  memberInitial: { minWidth: 24, height: 20, borderRadius: 10, backgroundColor: colors.border, alignItems: "center", justifyContent: "center", paddingHorizontal: 4, overflow: "hidden" },
  memberInitialChecked: { backgroundColor: colors.primary },
  memberInitialText: { fontSize: 10, fontWeight: "600", color: colors.muted },
  memberInitialTextChecked: { color: "#ffffff" },
  memberImageWrapper: { width: 24, height: 24, borderRadius: 12, overflow: "hidden", alignItems: "center", justifyContent: "center" },
  memberImageWrapperChecked: { borderWidth: 2, borderColor: colors.primary },
  memberImage: { width: 20, height: 20, borderRadius: 10 },
  memberImageOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(255,255,255,0.6)", borderRadius: 10 },
  menuButton: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  menuIcon: { fontSize: 20, color: colors.muted, fontWeight: "700" },
  empty: { alignItems: "center", paddingVertical: spacing.md },
  emptyText: { fontSize: 16, color: colors.muted, fontWeight: "500", textAlign: "center" },
  swipeAction: { width: spacing.lg * 3 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(17,24,39,0.4)", justifyContent: "center", alignItems: "center", padding: spacing.lg },
  modalCard: { width: "100%", maxWidth, backgroundColor: colors.surface, borderRadius: homeRadius, padding: spacing.lg, gap: spacing.md },
  modalTitle: { fontSize: 18, fontWeight: "700", color: colors.text },
  modalLabel: { fontSize: 14, fontWeight: "500", color: colors.muted },
  modalInput: { borderWidth: 1, borderColor: colors.border, borderRadius: homeRadius / 2, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, fontSize: 16, color: colors.text },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: spacing.sm },
  modalAction: { fontSize: 16, fontWeight: "600", color: colors.muted },
  modalActionPrimary: { color: colors.primary },
  itemDragHandle: { width: spacing.lg, height: spacing.lg, alignItems: "center", justifyContent: "center" },
  itemDragHandleIcon: { fontSize: 18, color: colors.muted },
  itemGhost: { position: "absolute", zIndex: 10, elevation: 5, opacity: 0.85, backgroundColor: colors.surface, borderRadius: homeRadius / 2, left: spacing.xs, right: spacing.xs },
  itemIndicator: { position: "absolute", left: 0, right: 0, height: 2, backgroundColor: "#000000", borderRadius: 1, zIndex: 15 },
});
