default_platform(:ios)

platform :ios do
  desc "Generate App Store screenshots"
  lane :screenshots do
    snapshot
    frame_screenshots
  end

  desc "Add device frames and text to screenshots"
  lane :frame_screenshots do
    frameit(
      path: "./fastlane/screenshots/en-US",
      white: true
    )
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    upload_to_app_store(
      app_identifier: "se.kodsam.packsmarter",
      skip_binary_upload: true,
      skip_metadata: true,
      screenshots_path: "./fastlane/screenshots",
    )
  end
end
